version: 0.2
env:
  variables:
    VITE_API_URL: "https://customer-support.snehasis.com"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - pnpm run build
artifacts:
  files:
    - "dist/**/*"
    - "scripts/**"
    - "appspec.yml"
